readme/instructor guide for workshop
visualizingthefuture/ethics-in-data-viz pull request #1
Opened 2021-05-28 22:10 UTC by zoews

Hi all,

Here's a place for us to discuss the readme (which i've formatted here as a lightweight instructor guide). What would you like to see in this guide? Feel free to add ideas here or commit to this branch. Thanks!

2021-06-15 18:14 UTC, amzoss requested changes
I'm happy to help with any/all of these changes after PR merge, too! Either way works.

2021-06-15 18:14 UTC, amzoss commented on README.md
> +This work is part of the IMLS-funded [Visualizing the Future](visualizingthefuture.github.io/) project.
The official statement should be:

This project was made possible in part by the [Institute of Museum and Library Services](https://www.imls.gov/), RE-73-18-0059-18.

2021-06-15 18:14 UTC, amzoss commented on README.md
> +This hour-long workshop (undergrad and grad level) provides an introduction to ethics in data visualization. Please feel free to use this workshop, repurpose and remix this content, add suggestions t
Maybe remove reference to hour-long, since there are a variety of ways to run the workshop.

2021-06-15 18:14 UTC, amzoss commented on README.md
> +
Add section that specifies the suggested times for different parts of the workshop:

Lecture: 15-20 min lecturing, including individual/small group reflection questions
1st Activity - Mississippi Census maps (full group): 15-20 min
2nd Activity - Economist makeovers (small group): 30-50 min

2021-06-15 18:14 UTC, amzoss commented on README.md
> +We provide two starting points for teaching Ethics in Data Visualization:"
Extra " at the end of line?

2021-06-15 18:22 UTC, grynoch commented on README.md
> +We've included a variety of materials to make in-person instruction easier, and also to help you excerpt some of the activities and ideas here for use in another course. These include:
These materials can also help with online instruction

2021-06-22 18:23 UTC, zoews commented
Thanks @amzoss @grynoch ! Added your suggestions here.

2021-06-22 18:28 UTC, amzoss approved these changes

2021-06-22 18:28 UTC, merged